version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DATABASE_NAME}
      - DB_USERNAME=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_USER_PASSWORD}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
